# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8d154672bed45a7b540994ac0fe287fffa217a442a15317b990f5bf6ee9619289a6cb9f828f0301c54497b933434d3b2b2d8879ba7b52c9dedc686a44057b98

test:
  secret_key_base: 45baaf03a3d9e99093b3702d0cafa7a68f261c2da6acd625d650fdfaa1d13bb62b82ab1c5f542fbe836a8c5f31ba85e63ddc471174056bed26792997d4c1ce44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
